[package]
name = "kludged"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.13"
hidapi = "2.6.1"
palette = {version = "0.7.5", default-features=false, features=["libm", "named", "named_from_str"]}
strum = { version = "0.26.2", features = ["derive"] }
