use crate::keyboards::steps::{same_step_indexes, Indexes};
use strum::EnumIter;

#[rustfmt::skip]
#[derive(EnumIter)]
pub enum Keys {
    Esc, Num1, Num2, Num3, Num4, Num5, Num6, Num7, Num8, Num9, Num0, Dash, Equals, BackSpace, Tilde,
    Tab, Q, W, E, R, T, Y, U, I, O, P, OpenAngleBracket, CloseAngleBracket, Backslash, Del,
    CpsLock, A, S, D, F, G, H, J, K, L, SemiColon, Apostrophe, Enter, PgUp,
    LeftShift, Z, X, C, V, B, N, M, Comma, Period, Slash, RightShift, UpArrow, PgDown,
    LeftCtrl, Super, LeftAlt, Space, RightAlt, Function, RightCtrl, LeftArrow, DownArrow, RightArrow,
}

impl Keys {
    pub const fn indexes(&self) -> [Indexes; 3] {
        match self {
            Self::Esc => same_step_indexes(0, 9),
            Self::Tab => same_step_indexes(0, 12),
            Self::CpsLock => same_step_indexes(0, 15),
            Self::LeftShift => same_step_indexes(0, 18),
            Self::LeftCtrl => same_step_indexes(0, 21),
            Self::Num1 => same_step_indexes(0, 27),
            Self::Q => same_step_indexes(0, 30),
            Self::A => same_step_indexes(0, 33),
            Self::Z => same_step_indexes(0, 36),
            Self::Super => same_step_indexes(0, 39),
            Self::Num2 => same_step_indexes(0, 45),
            Self::W => same_step_indexes(0, 48),
            Self::S => same_step_indexes(0, 51),
            Self::X => same_step_indexes(0, 54),
            Self::LeftAlt => same_step_indexes(0, 57),
            Self::Num3 => [Indexes::new(0, 63), Indexes::new(0, 64), Indexes::new(1, 3)],
            Self::E => same_step_indexes(1, 4),
            Self::D => same_step_indexes(1, 7),
            Self::C => same_step_indexes(1, 10),
            Self::Num4 => same_step_indexes(1, 19),
            Self::R => same_step_indexes(1, 22),
            Self::F => same_step_indexes(1, 25),
            Self::V => same_step_indexes(1, 28),
            Self::Num5 => same_step_indexes(1, 37),
            Self::T => same_step_indexes(1, 40),
            Self::G => same_step_indexes(1, 43),
            Self::B => same_step_indexes(1, 46),
            Self::Space => same_step_indexes(1, 49),
            Self::Num6 => same_step_indexes(1, 55),
            Self::Y => same_step_indexes(1, 58),
            Self::H => same_step_indexes(1, 61),
            Self::N => [Indexes::new(1, 64), Indexes::new(2, 3), Indexes::new(2, 4)],
            Self::Num7 => same_step_indexes(2, 11),
            Self::U => same_step_indexes(2, 14),
            Self::J => same_step_indexes(2, 17),
            Self::M => same_step_indexes(2, 20),
            Self::Num8 => same_step_indexes(2, 29),
            Self::I => same_step_indexes(2, 32),
            Self::K => same_step_indexes(2, 35),
            Self::Comma => same_step_indexes(2, 38),
            Self::RightAlt => same_step_indexes(2, 41),
            Self::Num9 => same_step_indexes(2, 47),
            Self::O => same_step_indexes(2, 50),
            Self::L => same_step_indexes(2, 53),
            Self::Period => same_step_indexes(2, 56),
            Self::Function => same_step_indexes(2, 59),
            Self::Num0 => same_step_indexes(3, 3),
            Self::P => same_step_indexes(3, 6),
            Self::SemiColon => same_step_indexes(3, 9),
            Self::Slash => same_step_indexes(3, 12),
            Self::RightCtrl => same_step_indexes(3, 15),
            Self::Dash => same_step_indexes(3, 21),
            Self::OpenAngleBracket => same_step_indexes(3, 24),
            Self::Apostrophe => same_step_indexes(3, 27),
            Self::RightShift => same_step_indexes(3, 30),
            Self::Equals => same_step_indexes(3, 39),
            Self::CloseAngleBracket => same_step_indexes(3, 42),
            Self::BackSpace => same_step_indexes(3, 57),
            Self::Backslash => same_step_indexes(3, 60),
            Self::Enter => [Indexes::new(3, 63), Indexes::new(3, 64), Indexes::new(4, 3)],
            Self::LeftArrow => same_step_indexes(4, 7),
            Self::UpArrow => same_step_indexes(4, 22),
            Self::DownArrow => same_step_indexes(4, 25),
            Self::Tilde => same_step_indexes(4, 31),
            Self::Del => same_step_indexes(4, 34),
            Self::PgUp => same_step_indexes(4, 37),
            Self::PgDown => same_step_indexes(4, 40),
            Self::RightArrow => same_step_indexes(4, 43),
        }
    }
}
